apiVersion: v1
kind: PersistentVolume
metadata:
  name: besu-2-data-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  hostPath:
    path: /Users/subash/workspace/besu-test-network/tst-cluster/mnt/data/ibft-node-2
