global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["10.108.34.241:9090"]
  - job_name: besu
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - 10.101.198.185:8545
  - job_name: push-gateway
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - 10.108.156.244:9091
